// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "fireworks", 
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "fireworks",
            targets: ["AppModule"],
            bundleIdentifier: "Victor.fireworks",
            teamIdentifier: "M67J2XKW43",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .pencil),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,

            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
   
                .process("Resources")
            ]
        )
    ]
)
